start:
	@echo "starting local server... 🦄⚡️"
	uvicorn app.main:app --reload --port 8000

black:
	@echo "Black formatting files...✅ 🤩"
	python -m black ./

sorter:
	@echo "Sorting imports...🧵"
	python -m isort ./
